# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'AlgorithmGame' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'ESTabBarController-swift'
  pod 'CollectionKit'
  pod 'Kingfisher'
  pod 'HandyJSON'
  pod 'SnapKit'
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'ProgressHUD'
  # Pods for AlgorithmGame

end
